"""Ferramentas para descobrir e selecionar sessões abertas do SAP GUI."""

from .connector import (
    InvalidSapSessionError,
    InvalidSessionSelectionError,
    NoSapConnectionsError,
    NoSapSessionsError,
    SapComError,
    SapConnector,
    SapConnectorError,
    SapDependencyError,
    SapGuiNotRunningError,
    SapScriptingUnavailableError,
    SapSessionInfo,
)
from .screen_reader import (
    SapScreenMonitor,
    SapScreenReader,
    SapScreenState,
    format_screen_state,
)
from .object_tree import (
    CORE_OBJECT_TREE_PROPERTIES,
    OBJECT_TREE_PROPERTIES,
    SapObjectTreeReader,
    SapTextContext,
    SapUiNode,
    SapUiTree,
    default_text_sanitizer,
    normalize_object_tree_payload,
    render_tree_summary,
)
from .fingerprint import (
    FINGERPRINT_SCHEMA_VERSION,
    ScreenFingerprint,
    build_content_payload,
    build_structural_payload,
    fingerprint_screen,
    normalize_component_id,
)
from .events import (
    GUI_SESSION_EVENTS,
    SapActionEvent,
    SapRawEvent,
    SapRecordedCommand,
    SapSessionEventSink,
    format_action_event,
    normalize_command_array,
    normalize_sap_event,
)
from .action_recorder import (
    SapActionRecorder,
    SapEventBindingError,
    SapEventError,
    SapEventThreadError,
    SapRecorderCapabilities,
)
from .models import SapScreenObservation, SapTransition
from .screen_reader import SapStatusBar
from .transition_recorder import SapSnapshotReader, SapTransitionRecorder
from .repository import SapRepository
from .sanitization import SanitizationPolicy

__all__ = [
    "SapScreenObservation",
    "SapTransition",
    "SapStatusBar",
    "SapSnapshotReader",
    "SapTransitionRecorder",
    "SapRepository",
    "SanitizationPolicy",
    "InvalidSapSessionError",
    "InvalidSessionSelectionError",
    "NoSapConnectionsError",
    "NoSapSessionsError",
    "SapComError",
    "SapConnector",
    "SapConnectorError",
    "SapDependencyError",
    "SapGuiNotRunningError",
    "SapScriptingUnavailableError",
    "SapSessionInfo",
    "SapScreenMonitor",
    "SapScreenReader",
    "SapScreenState",
    "format_screen_state",
    "CORE_OBJECT_TREE_PROPERTIES",
    "OBJECT_TREE_PROPERTIES",
    "SapObjectTreeReader",
    "SapTextContext",
    "SapUiNode",
    "SapUiTree",
    "default_text_sanitizer",
    "normalize_object_tree_payload",
    "render_tree_summary",
    "FINGERPRINT_SCHEMA_VERSION",
    "ScreenFingerprint",
    "build_content_payload",
    "build_structural_payload",
    "fingerprint_screen",
    "normalize_component_id",
    "GUI_SESSION_EVENTS",
    "SapActionEvent",
    "SapRawEvent",
    "SapRecordedCommand",
    "SapSessionEventSink",
    "format_action_event",
    "normalize_command_array",
    "normalize_sap_event",
    "SapActionRecorder",
    "SapEventBindingError",
    "SapEventError",
    "SapEventThreadError",
    "SapRecorderCapabilities",
]
